planning_pipelines:
  pipeline_names:
    - ompl

ompl:
  planning_plugin: ompl_interface/OMPLPlanner
  request_adapters: >-
    default_planner_request_adapters/ResolveConstraintFrames
    default_planner_request_adapters/FixWorkspaceBounds
    default_planner_request_adapters/FixStartStateBounds
    default_planner_request_adapters/FixStartStateCollision
    default_planner_request_adapters/AddTimeOptimalParameterization
  response_adapters: ""
  start_state_max_bounds_error: 0.1
  arm:
    planner_configs:
      - RRTConnectkConfigDefault
      - RRTkConfigDefault
  planner_configs:
    RRTConnectkConfigDefault:
      type: geometric::RRTConnect
      range: 0.0
    RRTkConfigDefault:
      type: geometric::RRT
      range: 0.0
      goal_bias: 0.05
