<?xml version="1.0"?>
<package format="3">
  <name>robot_arm_bringup</name>
  <version>1.0.0</version>
  <description>Launch files, configs and simulation resources for eMeet robotic arm</description>
  <maintainer email="support@emeet.com">EMEET Team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_arm_driver</exec_depend>
  <exec_depend>robot_arm_description</exec_depend>
  <exec_depend>robot_arm_node</exec_depend>
  <exec_depend>robot_arm_debug</exec_depend>
  <exec_depend>robot_arm_interfaces</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
